# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcSetup < Formula
  desc "Interactive CLI to manage MCP servers for Claude Code"
  homepage "https://github.com/rhuss/cc-setup"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.3.0/cc-setup-0.3.0-darwin-amd64.tar.gz"
      sha256 "6c8ea3ea3091fc595032c8bf996a5ea80bd4d0e899070440c3c384f41f88cb8c"

      define_method(:install) do
        bin.install "cc-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.3.0/cc-setup-0.3.0-darwin-arm64.tar.gz"
      sha256 "9fe094a091b2c8eddb110cb371c59afc062f1695848b2dd7fccd56c6fffb3e8c"

      define_method(:install) do
        bin.install "cc-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.3.0/cc-setup-0.3.0-linux-amd64.tar.gz"
      sha256 "0b54d28ac62f4f66207b60c313de0567f89d43281dc739ba2653989e9cd79084"
      define_method(:install) do
        bin.install "cc-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.3.0/cc-setup-0.3.0-linux-arm64.tar.gz"
      sha256 "bdfaa82336a4b15903a8041937bb2a663ef243e0ce54b77bca283faaa628299e"
      define_method(:install) do
        bin.install "cc-setup"
      end
    end
  end

  test do
    system "#{bin}/cc-setup", "version"
  end
end
