# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcSetup < Formula
  desc "Interactive CLI to manage MCP servers for Claude Code"
  homepage "https://github.com/rhuss/cc-setup"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.1.0/cc-setup-0.1.0-darwin-amd64.tar.gz"
      sha256 "9068e989b21380a69b15b886a63a4614b4838f5210805e916ff0739290833436"

      def install
        bin.install "cc-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.1.0/cc-setup-0.1.0-darwin-arm64.tar.gz"
      sha256 "fb667b11663ee00f39653c0cfa57a8f27455c7db16007be086c5efb27f8d108a"

      def install
        bin.install "cc-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.1.0/cc-setup-0.1.0-linux-amd64.tar.gz"
      sha256 "2606ec11ee27b0060e378ccd02fa7ddd2c37a781f56bc4c5c998e1ff75ff0231"
      def install
        bin.install "cc-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhuss/cc-setup/releases/download/v0.1.0/cc-setup-0.1.0-linux-arm64.tar.gz"
      sha256 "893b5d3fe2660df9f053045fdcd5bfc888deed15c3731647ddb4c95bba5077a5"
      def install
        bin.install "cc-setup"
      end
    end
  end

  test do
    system "#{bin}/cc-setup", "version"
  end
end
